### ISSUE TITLE
Missing internet permission

### ISSUE THREAD

**Issue by Germain-L** [varamsky/wallsky#1]
tried running the app on release mode `flutter build apk` 

app doesn't load any images.

This is because you need to add:
`<uses-permission android:name="android.permission.INTERNET" />`

in `android\app\src\main\AndroidManifest.xml`

**Comment by varamsky** [comment]
I hadn't paid attention to that, Thanks for the suggestion.
Actually, I had been running it on debug mode and it worked just fine.

Anyways, I have added the statement, so I'm closing this issue thread.
